#include "activity_internal.h"

/* statuemaze_clue: Static dialogue, messages generated by statuemaze.
 */
 
void begin_statuemaze_clue(struct sprite *initiator,int arg) {
  char tmp[256];
  int tmpc=statuemaze_get_message(tmp,sizeof(tmp),arg);
  if ((tmpc<0)||(tmpc>=sizeof(tmp))) return;
  struct modal_args_dialogue args={
    .text=tmp,
    .textc=tmpc,
    .speaker=initiator,
  };
  modal_spawn(&modal_type_dialogue,&args,sizeof(args));
}
