#include "activity_internal.h"

/* statuemaze_clue: Static dialogue, messages generated by statuemaze.
 */
 
void begin_statuemaze_clue(struct sprite *initiator,int arg) {
  char tmp[256];
  int tmpc=statuemaze_get_message(tmp,sizeof(tmp),arg);
  if ((tmpc<0)||(tmpc>=sizeof(tmp))) return;
  struct modal_args_dialogue args={
    .text=tmp,
    .textc=tmpc,
    .speaker=initiator,
  };
  modal_spawn(&modal_type_dialogue,&args,sizeof(args));
}

/* Mr and Mrs Rabbit.
 */

void begin_mr_mrs_rabbit(struct sprite *initiator,int arg) {
  
  /* When the quest is complete, we either say thanks or offer a clue to some other quest.
   * Mr or Mrs, same behavior.
   */
  if (store_get_fld(NS_fld_surveyor_complete)) {
    struct modal_args_dialogue args={
      .rid=RID_strings_dialogue,
      .strix=172, // Default "thanks!"
      .speaker=initiator,
    };
    if (!store_get_fld(NS_fld_zoo17_3)) { // Haven't captured an Eight at the southeast zoo. Let's assume they haven't noticed the figure-eight trick.
      args.strix=192;
    }
    modal_spawn(&modal_type_dialogue,&args,sizeof(args));
    return;
  }
  
  /* I was going to have Mrs Rabbit tell you "too high" or "too low" when all three are guessed, but that's tricky.
   * See surveyor.c:surveyor_check(). The distance and tolerance don't live anywhere we can easily find them.
   * This gag remains possible, but now I don't think it's worth the effort.
   */
  
  /* Simple dialogue, a different message per speaker.
   */
  struct modal_args_dialogue args={
    .rid=RID_strings_dialogue,
    .strix=170,
    .speaker=initiator,
  };
  if (arg==2) args.strix=171;
  modal_spawn(&modal_type_dialogue,&args,sizeof(args));
}
